project_name: tenderly
builds:
  - env:
      - CGO_ENABLED=0
  - id: tenderly-windows
    goos:
      - windows
    goarch:
      - amd64
      - arm

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - name: tenderly
    tap:
      owner: Tenderly
      name: homebrew-tenderly
    commit_author:
      name: Tenderly bot
      email: hi@tenderly.co
    homepage: "https://github.com/Tenderly/tenderly-cli"
    description: "Tenderly helps you observe your contracts in any environment."
    install: |
      bin.install "tenderly"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge remote-tracking branch'
